# Generated by Django 3.0.5 on 2020-04-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('texture', models.CharField(max_length=200)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rul.Palette')),
            ],
        ),
    ]
