# Generated by Django 3.0.5 on 2020-04-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0003_palette_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shade',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('C', 'Cyan'), ('V', 'Violet'), ('B', 'Black'), ('Br', 'Brown'), ('W', 'White'), ('S', 'Silver'), ('Go', 'Gold')], max_length=200),
        ),
        migrations.AlterField(
            model_name='shade',
            name='texture',
            field=models.CharField(choices=[('M', 'Matte'), ('Sh', 'Shimmer'), ('Sp', 'Sparkle'), ('G', 'Glitter'), ('T', 'Topper'), ('F', 'Foil')], max_length=200),
        ),
    ]
