# Generated by Django 3.0.5 on 2020-04-06 12:04

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0005_shade_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shade',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '40x40', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
