# Generated by Django 3.0.5 on 2020-04-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0007_shade_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shade',
            name='darkness',
            field=models.CharField(choices=[('1', 'Blackl'), ('2', 'dark'), ('3', 'medium'), ('4', 'light'), ('5', 'white')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shade',
            name='second_color',
            field=models.CharField(blank=True, choices=[('P', 'Pinc'), ('Co', 'Corall'), ('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('C', 'Cyan'), ('V', 'Violet'), ('B', 'Black'), ('Br', 'Brown'), ('W', 'White'), ('S', 'Silver'), ('Go', 'Gold')], max_length=200),
        ),
        migrations.AlterField(
            model_name='shade',
            name='color',
            field=models.CharField(choices=[('P', 'Pinc'), ('Co', 'Corall'), ('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('C', 'Cyan'), ('V', 'Violet'), ('B', 'Black'), ('Br', 'Brown'), ('W', 'White'), ('S', 'Silver'), ('Go', 'Gold')], max_length=200),
        ),
    ]
