# Generated by Django 3.0.5 on 2020-04-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='palette',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rul.Seller'),
        ),
    ]
