# Generated by Django 3.0.5 on 2020-04-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0002_auto_20200405_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='photo',
            field=models.ImageField(blank=True, upload_to='palettes'),
        ),
    ]
