# Generated by Django 3.0.5 on 2020-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0004_auto_20200406_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='shade',
            name='photo',
            field=models.ImageField(blank=True, upload_to='shades'),
        ),
    ]
