# Generated by Django 3.0.5 on 2020-04-14 10:50

from django.db import migrations, models
import rul.storage


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0009_auto_20200409_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shade',
            name='color',
            field=models.CharField(choices=[('P', 'Pink'), ('L', 'Lilac'), ('Co', 'Corall'), ('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('C', 'Cyan'), ('V', 'Violet'), ('Pu', 'Purple'), ('Bk', 'Black'), ('Br', 'Brown'), ('Be', 'Beige'), ('Gr', 'Gray'), ('W', 'White'), ('S', 'Silver'), ('Co', 'Cooper'), ('Go', 'Gold')], max_length=200),
        ),
        migrations.AlterField(
            model_name='shade',
            name='photo',
            field=models.ImageField(blank=True, storage=rul.storage.CustomStorage(), upload_to='shades'),
        ),
        migrations.AlterField(
            model_name='shade',
            name='second_color',
            field=models.CharField(blank=True, choices=[('P', 'Pink'), ('L', 'Lilac'), ('Co', 'Corall'), ('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('C', 'Cyan'), ('V', 'Violet'), ('Pu', 'Purple'), ('Bk', 'Black'), ('Br', 'Brown'), ('Be', 'Beige'), ('Gr', 'Gray'), ('W', 'White'), ('S', 'Silver'), ('Co', 'Cooper'), ('Go', 'Gold')], max_length=200),
        ),
    ]
