# Generated by Django 3.0.5 on 2020-04-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0013_usershade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPalette',
        ),
    ]
