# Generated by Django 3.0.5 on 2020-04-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rul', '0014_delete_userpalette'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('color_names', models.CharField(blank=True, max_length=200)),
                ('number_of_colors', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
