# Generated by Django 3.0.5 on 2020-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0015_paletterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletterequest',
            name='processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
