# Generated by Django 3.0.5 on 2020-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0017_paletterequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paletterequest',
            name='color_names',
        ),
        migrations.AddField(
            model_name='paletterequest',
            name='photo_URL',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
