# Generated by Django 3.0.5 on 2020-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0018_auto_20200421_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
